global:
  scrape_interval:     5s 
  evaluation_interval: 15s 

rule_files:
  - "/etc/prometheus/alerts.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - '127.0.0.1:9093'

scrape_configs:
  - job_name: 'fridge'
    static_configs:
      - targets: ['YOUR_PI_IP:5000']
