version: '3.1'

networks:
  monitor-net:

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - "/data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/data/prometheus/alerts.yml:/etc/prometheus/alerts.yml"
      - "/data/prometheus/:/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitor-net
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - "/data/alertmanager/:/etc/alertmanager/"
    networks:
      - monitor-net
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - /data/grafana:/var/lib/grafana
      - /data/grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - monitor-net
    restart: always
